- hosts: localhost
  remote_user: root

  vars:
    GUID: 9e88

  tasks:
  - name: "Project切り替え"
    shell: oc project pipeline-{{GUID}}-dev

  - name: "image streamタグ付け-DEV"
    shell: "oc tag cotd:latest cotd:testready -n pipeline-{{GUID}}-dev"
    ignore_errors: yes

  - name: "image streamタグ付け-Prod"
    shell: "oc tag cotd:testready cotd:prodready -n pipeline-{{GUID}}-dev"
    ignore_errors: yes

  - name: "Testへアプリケーションをリリース"
    shell: oc new-app pipeline-{{GUID}}-dev/cotd:testready --name=cotd -n pipeline-{{GUID}}-test
    ignore_errors: yes

  - name: "Prodへアプリケーションをリリース"
    shell: oc new-app pipeline-{{GUID}}-dev/cotd:prodready --name=cotd -n pipeline-{{GUID}}-prod
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Dev"
    shell: "oc get dc cotd -o yaml -n pipeline-{{GUID}}-dev | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Test"
    shell: "oc get dc cotd -o yaml -n pipeline-{{GUID}}-test | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Prod"
    shell: "oc get dc cotd -o yaml -n pipeline-{{GUID}}-prod | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "サービス公開-Dev"
    shell: oc expose service cotd -n pipeline-{{GUID}}-dev
    ignore_errors: yes

  - name: "サービス公開-Test"
    shell: oc expose service cotd -n pipeline-{{GUID}}-test
    ignore_errors: yes

  - name: "サービス公開-Prod"
    shell: oc expose service cotd -n pipeline-{{GUID}}-prod
    ignore_errors: yes

  - name: "パイプラインビルド定義"
    shell: oc create -f pipeline-demo
    ignore_errors: yes
