- hosts: localhost
  remote_user: root

  vars:

  tasks:
  - name: branch
    pause:
     prompt: "OCPのログインパスワードを入力"
    register: branch_input

  - name: "login OCP"
    shell: oc login https://master.na37.openshift.opentlc.com -u sanzai-redhat.com -p "{{ branch_input.user_input }}"

  - name: "Project 作成"
    shell: oc new-project demo-${GUID}

  - name: "Build"
    shell: cat Dockerfile | oc new-build --dockerfile=- --to=sleep

  - name: wait for the server to come up
    local_action: wait_for delay=10

  - name: "アプリケーション作成"
    shell: oc new-app sleep
