- hosts: localhost
  remote_user: root

  vars:
    GUID: 9e88

  tasks:
  - name: "Project切り替え"
    shell: oc project pipeline-{{GUID}}-dev

  - name: "image streamタグ付け-DEV"
    shell: "oc tag helloworld:latest helloworld:testready -n pipeline-{{GUID}}-dev"
    ignore_errors: yes

  - name: "image streamタグ付け-Prod"
    shell: "oc tag helloworld:testready helloworld:prodready -n pipeline-{{GUID}}-dev"
    ignore_errors: yes

  - name: "Testへアプリケーションをリリース"
    shell: oc new-app pipeline-{{GUID}}-dev/helloworld:testready --name=helloworld -n pipeline-{{GUID}}-test
    ignore_errors: yes

  - name: "Prodへアプリケーションをリリース"
    shell: oc new-app pipeline-{{GUID}}-dev/helloworld:prodready --name=helloworld -n pipeline-{{GUID}}-prod
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Dev"
    shell: "oc get dc helloworld -o yaml -n pipeline-{{GUID}}-dev | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Test"
    shell: "oc get dc helloworld -o yaml -n pipeline-{{GUID}}-test | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "automatic deploymentを無効化-Prod"
    shell: "oc get dc helloworld -o yaml -n pipeline-{{GUID}}-prod | sed 's/automatic: true/automatic: false/g' | oc replace -f -"
    ignore_errors: yes

  - name: "サービス公開-Test"
    shell: oc expose service helloworld -n pipeline-{{GUID}}-test
    ignore_errors: yes

  - name: "サービス公開-Prod"
    shell: oc expose service helloworld -n pipeline-{{GUID}}-prod
    ignore_errors: yes

  - name: "パイプラインビルド定義"
    shell: oc create -f pipeline-helloworld
    ignore_errors: yes
